const games=[
{id:"dragon",name:"Dragon Reef",type:"fish",icon:"🐉",desc:"Reef hunter"},
{id:"mermaid",name:"Mermaid Bay",type:"fish",icon:"🧜‍♀️",desc:"Fantasy ocean hunt"},
{id:"ocean",name:"Ocean Hunter",type:"fish",icon:"🦈",desc:"Deep-sea hunter"},
{id:"buffaloDeep",name:"Buffalo Deep",type:"fish",icon:"🐃",desc:"Wild reef hunt"},
{id:"fire",name:"Fire Vault",type:"slots",icon:"🔥",desc:"3-reel fire game"},
{id:"buffalo",name:"Golden Buffalo",type:"slots",icon:"🦬",desc:"Buffalo reels"},
{id:"fortune",name:"Dragon Fortune",type:"slots",icon:"🐲",desc:"Dragon reels"},
{id:"seven",name:"Neon 7s",type:"slots",icon:"7️⃣",desc:"Classic neon reels"}];
let credits=Number(localStorage.drCredits||5000),history=JSON.parse(localStorage.drHistory||"[]"),activeCleanup=null;
const $=s=>document.querySelector(s),grid=$("#grid");
function save(){localStorage.drCredits=credits;localStorage.drHistory=JSON.stringify(history);$("#credits").textContent=credits.toLocaleString();$("#gameCredits").textContent=credits.toLocaleString()}
function tx(n,label){credits+=n;history.unshift({n,label,t:new Date().toLocaleString()});history=history.slice(0,80);save()}
function render(filter="all"){grid.innerHTML="";games.filter(g=>filter==="all"||g.type===filter).forEach(g=>{let d=document.createElement("div");d.className="card";d.dataset.type=g.type;d.innerHTML=`<span class="badge">${g.type==="fish"?"FISH":"SLOTS"}</span><div class="art">${g.icon}</div><div class="info"><b>${g.name}</b><small>${g.desc}</small></div>`;d.onclick=()=>openGame(g);grid.appendChild(d)})}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)});
$("#back").onclick=()=>{if(activeCleanup)activeCleanup();activeCleanup=null;$("#modal").classList.add("hidden")};
$("#historyBtn").onclick=()=>{drawHistory();$("#history").classList.remove("hidden")};$("#closeHistory").onclick=()=>$("#history").classList.add("hidden");
$("#reset").onclick=()=>{credits=5000;history=[];save();drawHistory()};
function drawHistory(){let e=$("#historyRows");e.innerHTML=history.length?history.map(x=>`<div class="row"><span>${x.label}<small><br>${x.t}</small></span><b class="${x.n>=0?"plus":"minus"}">${x.n>=0?"+":""}${x.n}</b></div>`).join(""):"No plays yet."}
function openGame(g){if(activeCleanup)activeCleanup();$("#gameTitle").textContent=g.name;$("#modal").classList.remove("hidden");$("#gameArea").innerHTML="";activeCleanup=g.type==="fish"?fishGame(g):slotGame(g);save()}
function beep(freq=440,d=.05){try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),v=a.createGain();o.connect(v);v.connect(a.destination);o.frequency.value=freq;v.gain.value=.035;o.start();v.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch(e){}}
function fishGame(g){
 const area=$("#gameArea");area.innerHTML=`<div class="fishWrap pro"><div class="hud proHud"><span>STAGE <b id="level">1</b></span><span>WIN <b id="score">0</b></span><span>CHAIN <b id="combo">0</b>x</span><span class="bossMeter">DRAGON REEF</span><button id="pause">Ⅱ</button><button id="sound">🔊</button></div><div class="tankFrame"><canvas class="fishCanvas" width="1280" height="720"></canvas><div class="cornerLogo">DRAGON <i>REEF</i></div></div><div class="controls arcadeControls"><button id="down">−</button><span class="bet">CANNON <b id="shot">10</b></span><button id="up">+</button><button id="rapid">AUTO FIRE: OFF</button></div><div class="message" id="msg">Aim anywhere in the reef and fire. Larger creatures require more hits.</div></div>`;
 const canvas=area.querySelector("canvas"),ctx=canvas.getContext("2d"),shotEl=area.querySelector("#shot"),msg=area.querySelector("#msg");
 let bet=10,running=true,paused=false,sound=true,rapid=false,raf=0,last=performance.now(),spawnClock=0,level=1,score=0,combo=0,bossSpawned=false,pointer={x:640,y:330},rapidTimer=0,t=0,shake=0;
 const palette=["#ffb32d","#38d9ff","#f45b78","#b6e34b","#8e78ff","#ff7043","#3ed6a0"];
 const kinds=[
  {species:"butterfly",r:31,hp:1,m:2,s:1.35},{species:"snapper",r:38,hp:2,m:3,s:1.08},{species:"puffer",r:40,hp:2,m:4,s:.88},
  {species:"ray",r:52,hp:3,m:5,s:.72},{species:"turtle",r:54,hp:4,m:6,s:.62},{species:"shark",r:68,hp:6,m:9,s:.58}
 ];
 let fish=[],bullets=[],particles=[],rings=[],floaters=[],bubbles=Array.from({length:70},()=>({x:Math.random()*1280,y:Math.random()*720,r:.8+Math.random()*4,s:.2+Math.random()*.8,a:.15+Math.random()*.35}));
 function spawn(boss=false){let k=boss?{species:g.id==="dragon"?"dragon":"whale",r:118,hp:28,m:40,s:.30,boss:true}:kinds[Math.floor(Math.random()*kinds.length)],fromLeft=Math.random()<.5;fish.push({x:fromLeft?-k.r*1.5:1280+k.r*1.5,y:100+Math.random()*470,vx:(fromLeft?1:-1)*k.s*(1+level*.045),vy:(Math.random()-.5)*.20,...k,maxhp:k.hp,phase:Math.random()*9,color:palette[Math.floor(Math.random()*palette.length)]});}
 for(let i=0;i<14;i++){spawn();fish[i].x=Math.random()*1280}
 function fire(x,y){if(paused||credits<bet){if(credits<bet)msg.textContent="Not enough demo credits.";return}tx(-bet,`${g.name} shot`);let dx=x-640,dy=y-668,l=Math.hypot(dx,dy)||1;bullets.push({x:640,y:668,vx:dx/l*16,vy:dy/l*16,r:6,life:90,ang:Math.atan2(dy,dx)});pointer={x,y};rings.push({x:640,y:658,r:10,a:.8});if(sound)beep(540,.025)}
 function hit(f,b){f.hp--;b.life=0;shake=Math.min(8,shake+2);rings.push({x:b.x,y:b.y,r:8,a:1});for(let i=0;i<13;i++)particles.push({x:b.x,y:b.y,vx:(Math.random()-.5)*8,vy:(Math.random()-.5)*8,a:1,r:1+Math.random()*4,c:i%3?"#8ff6ff":"#ffe36c"});if(f.hp<=0){let award=bet*f.m;tx(award,`${g.name} ${f.boss?"boss":"target"} award`);score+=award;combo++;area.querySelector("#score").textContent=score.toLocaleString();area.querySelector("#combo").textContent=combo;floaters.push({x:f.x,y:f.y,text:`+${award}`,a:1,s:f.boss?38:24});msg.textContent=`${f.boss?"LEGENDARY BOSS DEFEATED":"TARGET CAPTURED"} • +${award} credits`;f.dead=true;if(sound)beep(f.boss?170:920,.12);if(score>=level*650){level++;area.querySelector("#level").textContent=level;bossSpawned=false}}}
 function reefPlant(x,y,h,c,phase){ctx.save();ctx.translate(x,y);ctx.strokeStyle=c;ctx.lineWidth=7;ctx.lineCap="round";for(let i=0;i<4;i++){ctx.beginPath();ctx.moveTo(0,0);ctx.quadraticCurveTo((i-1.5)*14+Math.sin(t*.002+phase+i)*10,-h*.55,(i-1.5)*18+Math.sin(t*.002+phase+i)*14,-h);ctx.stroke()}ctx.restore()}
 function drawBackground(){let g=ctx.createLinearGradient(0,0,0,720);g.addColorStop(0,"#087fa5");g.addColorStop(.28,"#075b82");g.addColorStop(.68,"#063550");g.addColorStop(1,"#021b2b");ctx.fillStyle=g;ctx.fillRect(0,0,1280,720);
  ctx.save();ctx.globalAlpha=.14;for(let i=0;i<7;i++){ctx.fillStyle="#d7fbff";ctx.beginPath();ctx.moveTo(80+i*205,0);ctx.lineTo(180+i*205,0);ctx.lineTo(390+i*170,650);ctx.lineTo(250+i*170,650);ctx.fill()}ctx.restore();
  let haze=ctx.createRadialGradient(640,250,20,640,300,600);haze.addColorStop(0,"#45dfff22");haze.addColorStop(1,"#00152200");ctx.fillStyle=haze;ctx.fillRect(0,0,1280,720);
  bubbles.forEach(b=>{b.y-=b.s;if(b.y<-10){b.y=730;b.x=Math.random()*1280}ctx.globalAlpha=b.a;ctx.strokeStyle="#d8fbff";ctx.lineWidth=1;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.stroke()});ctx.globalAlpha=1;
  ctx.fillStyle="#0b3340";ctx.beginPath();ctx.moveTo(0,645);for(let x=0;x<=1280;x+=45)ctx.lineTo(x,630+Math.sin(x*.021)*18+Math.sin(x*.053)*8);ctx.lineTo(1280,720);ctx.lineTo(0,720);ctx.fill();
  ctx.fillStyle="#124b51";for(let i=0;i<14;i++){let x=(i*103+35)%1280,y=648+Math.sin(i)*12;ctx.beginPath();ctx.ellipse(x,y,45+(i%3)*12,20,0,0,7);ctx.fill()}
  reefPlant(90,680,110,"#c75570",1);reefPlant(185,688,82,"#ef9b3b",2);reefPlant(1090,688,105,"#8c5bc7",3);reefPlant(1190,690,75,"#d55d52",4);reefPlant(1010,692,62,"#3fae83",5);
  ctx.fillStyle="#c7a05c";ctx.beginPath();ctx.ellipse(640,692,150,20,0,0,7);ctx.fill();ctx.fillStyle="#254a4b";ctx.fillRect(420,653,90,15);ctx.fillRect(775,660,105,12)
 }
 function bodyGradient(f){let grad=ctx.createLinearGradient(-f.r,0,f.r,0);grad.addColorStop(0,"#142c3a");grad.addColorStop(.35,f.color);grad.addColorStop(.68,"#e9f5c8");grad.addColorStop(1,f.color);return grad}
 function drawFish(f){ctx.save();ctx.translate(f.x,f.y);if(f.vx<0)ctx.scale(-1,1);let r=f.r,w=r*1.55,h=r*.72,sw=Math.sin(t*.012+f.phase)*.16;
  if(f.species==="ray"){ctx.fillStyle=bodyGradient(f);ctx.beginPath();ctx.moveTo(-w*.7,0);ctx.quadraticCurveTo(0,-h*1.1,w*.72,0);ctx.quadraticCurveTo(0,h*1.05,-w*.7,0);ctx.fill();ctx.strokeStyle=f.color;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-w*.65,0);ctx.quadraticCurveTo(-w*1.3,15+sw*30,-w*1.65,4);ctx.stroke();}
  else if(f.species==="turtle"){ctx.fillStyle="#3f8c67";ctx.beginPath();ctx.ellipse(0,0,w*.65,h*.72,0,0,7);ctx.fill();ctx.fillStyle="#8ebd75";ctx.beginPath();ctx.ellipse(w*.7,-2,r*.25,r*.20,0,0,7);ctx.fill();for(let q of [[-.2,-.65],[.15,.65]]){ctx.save();ctx.rotate(q[1]);ctx.beginPath();ctx.ellipse(0,0,r*.62,r*.16,0,0,7);ctx.fill();ctx.restore()}ctx.strokeStyle="#b8d08a";ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,w*.48,h*.56,0,0,7);ctx.stroke()}
  else if(f.species==="shark"){ctx.fillStyle="#6f9eaa";ctx.beginPath();ctx.moveTo(-w*.95,0);ctx.lineTo(-w*1.35,-h*.55);ctx.lineTo(-w*1.22,0);ctx.lineTo(-w*1.38,h*.55);ctx.lineTo(-w*.9,0);ctx.quadraticCurveTo(0,-h*.72,w*.9,-h*.05);ctx.quadraticCurveTo(w*.55,h*.55,-w*.9,0);ctx.fill();ctx.fillStyle="#496f79";ctx.beginPath();ctx.moveTo(-r*.1,-h*.55);ctx.lineTo(r*.1,-h*1.25);ctx.lineTo(r*.38,-h*.5);ctx.fill()}
  else if(f.species==="puffer"){ctx.fillStyle=bodyGradient(f);ctx.beginPath();ctx.arc(0,0,r*.78,0,7);ctx.fill();ctx.strokeStyle="#d9ef9b";ctx.lineWidth=2;for(let a=0;a<6.28;a+=.45){ctx.beginPath();ctx.moveTo(Math.cos(a)*r*.72,Math.sin(a)*r*.72);ctx.lineTo(Math.cos(a)*r*.98,Math.sin(a)*r*.98);ctx.stroke()}ctx.fillStyle=f.color;ctx.beginPath();ctx.moveTo(-r*.72,0);ctx.lineTo(-r*1.25,-r*.55);ctx.lineTo(-r*1.18,r*.55);ctx.fill()}
  else if(f.species==="dragon"){ctx.shadowColor="#ffd43b";ctx.shadowBlur=25;ctx.strokeStyle="#f3b52b";ctx.lineWidth=r*.28;ctx.lineCap="round";ctx.beginPath();for(let i=0;i<7;i++){let x=-r*1.2+i*r*.38,y=Math.sin(t*.006+f.phase+i*.8)*r*.24; i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#d84b31";ctx.beginPath();ctx.ellipse(r*.72,0,r*.55,r*.38,0,0,7);ctx.fill();ctx.fillStyle="#f2c74d";ctx.beginPath();ctx.moveTo(r*.8,-r*.25);ctx.lineTo(r*1.2,-r*.65);ctx.lineTo(r*1.05,-r*.12);ctx.fill();ctx.beginPath();ctx.moveTo(r*.55,-r*.3);ctx.lineTo(r*.55,-r*.85);ctx.lineTo(r*.8,-r*.35);ctx.fill()}
  else if(f.species==="whale"){ctx.fillStyle="#4a83a8";ctx.beginPath();ctx.ellipse(0,0,w*.82,h*.82,0,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(-w*.7,0);ctx.lineTo(-w*1.25,-h*.7);ctx.lineTo(-w*1.05,0);ctx.lineTo(-w*1.25,h*.7);ctx.fill()}
  else {ctx.fillStyle=bodyGradient(f);ctx.beginPath();ctx.ellipse(0,0,w*.72,h*.72,0,0,7);ctx.fill();ctx.fillStyle=f.color;ctx.beginPath();ctx.moveTo(-w*.62,0);ctx.lineTo(-w*1.08,-h*(.72+sw));ctx.lineTo(-w*.98,h*(.72-sw));ctx.closePath();ctx.fill();ctx.globalAlpha=.65;ctx.beginPath();ctx.moveTo(-r*.05,-h*.6);ctx.lineTo(r*.12,-h*1.12);ctx.lineTo(r*.42,-h*.55);ctx.fill();ctx.globalAlpha=1}
  if(!["dragon","ray"].includes(f.species)){ctx.fillStyle="#07141b";ctx.beginPath();ctx.arc(w*.48,-h*.15,Math.max(3,r*.07),0,7);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(w*.50,-h*.18,Math.max(1,r*.025),0,7);ctx.fill()}
  if(f.species==="butterfly"){ctx.strokeStyle="#15252c";ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-r*.15,-h*.65);ctx.lineTo(r*.05,h*.65);ctx.stroke();ctx.beginPath();ctx.moveTo(r*.3,-h*.58);ctx.lineTo(r*.48,h*.55);ctx.stroke()}
  ctx.restore();if(f.hp<f.maxhp||f.boss){let bw=f.boss?r*1.8:r*1.35;ctx.fillStyle="#00131dcc";ctx.fillRect(f.x-bw/2,f.y-r-24,bw,8);ctx.fillStyle=f.boss?"#ffc83d":"#55f0b1";ctx.fillRect(f.x-bw/2,f.y-r-24,bw*(f.hp/f.maxhp),8);if(f.boss){ctx.font="bold 15px Arial";ctx.textAlign="center";ctx.fillStyle="#ffe9a0";ctx.fillText("REEF BOSS",f.x,f.y-r-32)}}}
 function drawCannon(){ctx.save();ctx.translate(640,681);let a=Math.atan2(pointer.y-681,pointer.x-640)+Math.PI/2;ctx.rotate(a);let gr=ctx.createLinearGradient(-22,0,22,0);gr.addColorStop(0,"#243e52");gr.addColorStop(.45,"#9fe9ff");gr.addColorStop(.6,"#315a72");gr.addColorStop(1,"#132838");ctx.fillStyle=gr;ctx.strokeStyle="#d9f7ff";ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(-22,-62,44,76,12);ctx.fill();ctx.stroke();ctx.fillStyle="#ffd33d";ctx.fillRect(-14,-58,28,12);ctx.restore();ctx.fillStyle="#0b2435";ctx.strokeStyle="#4fcdf1";ctx.lineWidth=3;ctx.beginPath();ctx.arc(640,681,42,Math.PI,0);ctx.fill();ctx.stroke();ctx.font="bold 15px Arial";ctx.fillStyle="#ffe269";ctx.textAlign="center";ctx.fillText(bet,640,699)}
 function loop(now){if(!running)return;let dt=Math.min(32,now-last);last=now;t=now;if(!paused){spawnClock+=dt;if(spawnClock>780){spawn();spawnClock=0}if(level>=2&&!bossSpawned&&score>=(level-1)*650+180){spawn(true);bossSpawned=true;msg.textContent="⚡ LEGENDARY CREATURE ENTERING THE REEF ⚡"}fish.forEach(f=>{f.x+=f.vx*dt*.06;f.y+=f.vy*dt*.06+Math.sin(now*.002+f.phase)*.08;if(f.x<-190||f.x>1470)f.dead=true});bullets.forEach(b=>{b.x+=b.vx;b.y+=b.vy;b.life--;fish.forEach(f=>{if(!f.dead&&b.life>0&&Math.hypot(f.x-b.x,f.y-b.y)<f.r*.78)hit(f,b)})});particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vx*=.96;p.vy*=.96;p.a-=.035});rings.forEach(r=>{r.r+=5;r.a-=.06});floaters.forEach(q=>{q.y-=.7;q.a-=.018});fish=fish.filter(f=>!f.dead);bullets=bullets.filter(b=>b.life>0&&b.x>-30&&b.x<1310&&b.y>-30&&b.y<750);particles=particles.filter(p=>p.a>0);rings=rings.filter(r=>r.a>0);floaters=floaters.filter(q=>q.a>0);if(rapid&&now-rapidTimer>190){fire(pointer.x,pointer.y);rapidTimer=now}}
  ctx.save();if(shake>0){ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawBackground();fish.forEach(drawFish);bullets.forEach(b=>{ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.ang);ctx.shadowColor="#63eaff";ctx.shadowBlur=14;ctx.fillStyle="#eaffff";ctx.beginPath();ctx.ellipse(0,0,11,4,0,0,7);ctx.fill();ctx.restore()});rings.forEach(r=>{ctx.globalAlpha=r.a;ctx.strokeStyle="#aaf7ff";ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,7);ctx.stroke();ctx.globalAlpha=1});particles.forEach(p=>{ctx.globalAlpha=p.a;ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill();ctx.globalAlpha=1});floaters.forEach(q=>{ctx.globalAlpha=q.a;ctx.font=`900 ${q.s}px Arial`;ctx.textAlign="center";ctx.strokeStyle="#10202c";ctx.lineWidth=5;ctx.strokeText(q.text,q.x,q.y);ctx.fillStyle="#ffe05a";ctx.fillText(q.text,q.x,q.y);ctx.globalAlpha=1});drawCannon();ctx.restore();if(paused){ctx.fillStyle="#00101ddd";ctx.fillRect(0,0,1280,720);ctx.fillStyle="#fff";ctx.font="900 54px Arial";ctx.textAlign="center";ctx.fillText("PAUSED",640,355)}raf=requestAnimationFrame(loop)}
 function pos(e){let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*1280/r.width,y:(p.clientY-r.top)*720/r.height}}
 function aim(e){e.preventDefault();pointer=pos(e)} function shoot(e){e.preventDefault();let p=pos(e);pointer=p;fire(p.x,p.y)}
 canvas.addEventListener("pointerdown",shoot);canvas.addEventListener("pointermove",aim);canvas.addEventListener("touchstart",shoot,{passive:false});
 area.querySelector("#down").onclick=()=>{bet=Math.max(5,bet-5);shotEl.textContent=bet};area.querySelector("#up").onclick=()=>{bet=Math.min(100,bet+5);shotEl.textContent=bet};area.querySelector("#pause").onclick=()=>{paused=!paused;area.querySelector("#pause").textContent=paused?"▶":"Ⅱ"};area.querySelector("#sound").onclick=()=>{sound=!sound;area.querySelector("#sound").textContent=sound?"🔊":"🔇"};area.querySelector("#rapid").onclick=e=>{rapid=!rapid;e.currentTarget.textContent=`AUTO FIRE: ${rapid?"ON":"OFF"}`};
 raf=requestAnimationFrame(loop);return()=>{running=false;cancelAnimationFrame(raf)}
}
function slotGame(g){
 const icons=g.id==="fire"?["🔥","💎","7️⃣","⭐","🍒"]:g.id==="buffalo"?["🦬","🌄","🦅","💰","A"]:g.id==="fortune"?["🐲","🪙","🏮","💎","A"]:["7️⃣","🍒","🔔","⭐","💎"];
 const area=$("#gameArea");area.innerHTML=`<div class="slotWrap"><div class="reels"><div class="reel">?</div><div class="reel">?</div><div class="reel">?</div></div><div class="controls"><button id="minus">−</button><span class="bet">SPIN <b id="stake">25</b></span><button id="plus">+</button></div><button class="spin" id="spin">SPIN</button><div class="message" id="slotMsg"></div><p>Three matching symbols award 10× the selected entertainment-credit spin amount; two matching symbols award 2×.</p></div>`;
 let stake=25;area.querySelector("#minus").onclick=()=>{stake=Math.max(5,stake-5);area.querySelector("#stake").textContent=stake};area.querySelector("#plus").onclick=()=>{stake=Math.min(100,stake+5);area.querySelector("#stake").textContent=stake};area.querySelector("#spin").onclick=()=>{if(credits<stake){area.querySelector("#slotMsg").textContent="Not enough demo credits.";return}tx(-stake,`${g.name} spin`);let a=[0,0,0].map(()=>icons[Math.floor(Math.random()*icons.length)]);area.querySelectorAll(".reel").forEach((r,i)=>r.textContent=a[i]);let award=0;if(a[0]===a[1]&&a[1]===a[2])award=stake*10;else if(a[0]===a[1]||a[1]===a[2]||a[0]===a[2])award=stake*2;if(award)tx(award,`${g.name} award`);area.querySelector("#slotMsg").textContent=award?`Award: +${award} credits`:"No match"};return()=>{}
}
render();save();
